apiVersion: v1
kind: ConfigMap
metadata:
  name: authz-config
data:
  R2DBC_URL: r2dbc:postgresql://postgres:5432/postgres
  DB_PASSWORD: db_password
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  LOGGING_LEVEL: INFO
  AUTHZ_CODE_SECRET: authz_code_secret
  NEXTJS_BASE_URL: https://www.macra.live