apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  rabbitmq.conf: |
    loopback_users = none
    management.load_definitions = /etc/rabbitmq/definitions.json
  enabled_plugins: |
    [rabbitmq_management].
  definitions.json: |
    {
      "rabbit_version": "3.9.10",
      "rabbitmq_version": "3.9.10",
      "users": [
        {
          "name": "admin",
          "password_hash": "rabbit_password_hashing_sha256",
          "hashing_algorithm": "rabbit_password_hashing_sha256",
          "tags": "administrator"
        }
      ],
      "vhosts": [
        {
          "name": "/"
        }
      ],
      "permissions": [
        {
          "user": "admin",
          "vhost": "/",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }
      ],
      "parameters": [],
      "policies": [],
      "queues": [
        {
          "name": "event-sync-queue",
          "vhost": "/",
          "durable": true,
          "auto_delete": false,
          "arguments": {}
        },
        {
          "name": "payment-event-queue",
          "vhost": "/",
          "durable": true,
          "auto_delete": false,
          "arguments": {}
        }
      ],
      "exchanges": [
        {
          "name": "event-sync-exchange",
          "vhost": "/",
          "type": "direct",
          "durable": true,
          "auto_delete": false,
          "internal": false,
          "arguments": {}
        },
        {
          "name": "payment-event-exchange",
          "vhost": "/",
          "type": "direct",
          "durable": true,
          "auto_delete": false,
          "internal": false,
          "arguments": {}
        }
      ],
      "bindings": [
        {
          "source": "event-sync-exchange",
          "vhost": "/",
          "destination": "event-sync-queue",
          "destination_type": "queue",
          "routing_key": "event-sync-key",
          "arguments": {}
        },
        {
          "source": "payment-event-exchange",
          "vhost": "/",
          "destination": "payment-event-queue",
          "destination_type": "queue",
          "routing_key": "payment-event-key",
          "arguments": {}
        }
      ]
    }